import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { app } from 'electron'
import { getCurrentWorkspaceId } from './workspaces'

export interface Cookie {
  domain: string
  name: string
  value: string
  path: string
  expires: number
  httpOnly: boolean
  secure: boolean
  sameSite?: 'Strict' | 'Lax' | 'None'
}

// Get cookies file path for profile
function getCookiesPath(profileId: string): string {
  const workspaceId = getCurrentWorkspaceId()
  return workspaceId
    ? join(app.getPath('userData'), 'workspaces', workspaceId, 'profiles', profileId, 'cookies.json')
    : join(app.getPath('userData'), 'profiles', profileId, 'cookies.json')
}

function writeCookies(profileId: string, cookies: Cookie[]): void {
  const cookiesPath = getCookiesPath(profileId)
  const dir = dirname(cookiesPath)
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true })
  }
  writeFileSync(cookiesPath, JSON.stringify(cookies, null, 2))
}

// Parse Netscape cookies.txt format
export function parseNetscapeCookies(content: string): Cookie[] {
  const cookies: Cookie[] = []
  const lines = content.split('\n')
  
  for (const line of lines) {
    if (!line || line.startsWith('#')) continue
    
    const parts = line.split('\t')
    if (parts.length < 7) continue
    
    cookies.push({
      domain: parts[0],
      httpOnly: parts[1] === 'TRUE',
      path: parts[2],
      secure: parts[3] === 'TRUE',
      expires: parseInt(parts[4]) * 1000,
      name: parts[5],
      value: parts[6]
    })
  }
  
  return cookies
}

// Convert cookies to Netscape format
export function toNetscapeFormat(cookies: Cookie[]): string {
  let content = '# Netscape HTTP Cookie File\n'
  content += '# This file was generated by Zenvy Browser\n\n'
  
  for (const cookie of cookies) {
    const parts = [
      cookie.domain,
      cookie.httpOnly ? 'TRUE' : 'FALSE',
      cookie.path,
      cookie.secure ? 'TRUE' : 'FALSE',
      Math.floor(cookie.expires / 1000).toString(),
      cookie.name,
      cookie.value
    ]
    content += parts.join('\t') + '\n'
  }
  
  return content
}

// Auto-detect and parse cookies (Netscape or JSON)
function parseAnyCookieFormat(content: string): Cookie[] {
  // Try JSON first
  try {
    const parsed = JSON.parse(content)
    if (Array.isArray(parsed)) {
      // Already in our format or similar
      return parsed.map(c => ({
        domain: c.domain || '',
        name: c.name || '',
        value: c.value || '',
        path: c.path || '/',
        expires: c.expires || c.expirationDate * 1000 || Date.now() + 365*24*60*60*1000,
        httpOnly: c.httpOnly || false,
        secure: c.secure || false,
        sameSite: c.sameSite
      }))
    }
  } catch {
    // Not JSON, try Netscape format
  }
  
  return parseNetscapeCookies(content)
}

// Import cookies from file
export function importCookies(profileId: string, filePath: string): Cookie[] {
  if (!existsSync(filePath)) {
    throw new Error('Cookie file not found')
  }
  
  const content = readFileSync(filePath, 'utf-8')
  const cookies = parseAnyCookieFormat(content)
  
  writeCookies(profileId, cookies)
  
  return cookies
}

// Export cookies to file
export function exportCookies(profileId: string, filePath: string): void {
  const cookiesPath = getCookiesPath(profileId)
  
  if (!existsSync(cookiesPath)) {
    throw new Error('No cookies found for this profile')
  }
  
  const cookies: Cookie[] = JSON.parse(readFileSync(cookiesPath, 'utf-8'))
  const content = toNetscapeFormat(cookies)
  
  writeFileSync(filePath, content)
}

// Get cookies for profile
export function getCookies(profileId: string): Cookie[] {
  const cookiesPath = getCookiesPath(profileId)
  
  if (!existsSync(cookiesPath)) {
    return []
  }
  
  return JSON.parse(readFileSync(cookiesPath, 'utf-8'))
}

// Set cookie for profile
export function setCookie(profileId: string, cookie: Cookie): void {
  const cookies = getCookies(profileId)
  
  // Update or add cookie
  const index = cookies.findIndex(c => c.domain === cookie.domain && c.name === cookie.name)
  if (index >= 0) {
    cookies[index] = cookie
  } else {
    cookies.push(cookie)
  }
  
  writeCookies(profileId, cookies)
}

// Delete cookie
export function deleteCookie(profileId: string, domain: string, name: string): void {
  const cookies = getCookies(profileId)
  const filtered = cookies.filter(c => !(c.domain === domain && c.name === name))
  
  writeCookies(profileId, filtered)
}

// Clear all cookies for profile
export function clearCookies(profileId: string): void {
  writeCookies(profileId, [])
}

// Sync cookies from Chrome session to storage
export function syncCookiesFromBrowser(profileId: string, chromeCookies: any[]): void {
  const cookies: Cookie[] = chromeCookies.map(c => ({
    domain: c.domain,
    name: c.name,
    value: c.value,
    path: c.path || '/',
    expires: c.expirationDate ? c.expirationDate * 1000 : Date.now() + 365*24*60*60*1000,
    httpOnly: c.httpOnly || false,
    secure: c.secure || false,
    sameSite: c.sameSite as any
  }))
  
  writeCookies(profileId, cookies)
}

export function replaceCookies(profileId: string, cookies: Cookie[]): void {
  writeCookies(profileId, cookies)
}
